### ISSUE TITLE
VfsExtFileSystem.GetFiles in a folder with \etc\mtab symbolic link throws "System.IO.FileNotFoundException: Unable to resolve symlink"

### ISSUE THREAD

**Issue by travist13** [DiscUtils/DiscUtils#141]
Hi Mike,

Here is the stack:
>System.IO.FileNotFoundException: Unable to resolve symlink
 File name: '\etc\mtab'
  at DiscUtils.Vfs.VfsFileSystem`4.ResolveSymlink(TDirEntry entry, String path)
  at DiscUtils.Vfs.VfsFileSystem`4.DoSearch(List`1 results, String path, Regex regex, Boolean subFolders, Boolean dirs, Boolean files)
  at DiscUtils.Vfs.VfsFileSystem`4.GetFiles(String path, String searchPattern, SearchOption searchOption)
  at Microsoft.AzureStack.Common.Tools.GuestLogCollectionTool.DiscUtilsFileSystem.<>c__DisplayClass9_0.<GetFiles>b__0() in
     C:\one\AzureStack\Common\Tools\src\GuestLogCollectionTool\Source\DiscUtilsFileSystem.cs:line 65
  at Microsoft.AzureStack.Common.Tools.GuestLogCollectionTool.DiscUtilsFileSystem.FileSystemExceptionHandler[T](Func`1 func, String exceptionFailureMessage, String targetPath) in
     C:\one\AzureStack\Common\Tools\src\GuestLogCollectionTool\Source\DiscUtilsFileSystem.cs:line 80
TargetObject          : \etc

The root /etc folder has several symbolic links and with two of them I am seeing failures in not finding the first link resolution path. The two examples I see are '\etc\mtab' and '\etc\resolve.conf'. I repro-ed this on CentOS 7.3 and UbuntuServer 1604 so far.

I did some debugging and the first symlink for mtab has a targetpath of '\proc\self\mounts' which doesn't exist using the FileSystem.FileExists() command.

I don't much care about the symlink file itself but it blocks getting any file from that folder as it throws a notfoundexception. Is there a workaround? I am using a set of filters to get the files and don't have the exact file names.

Thanks,
Travis

**Comment by LordMike** [comment]
Those paths work in the actual filesystem, with the backwards slashes? :O

As for the symlinks. I'm surprised we resolve the symlinks in the GetFiles() call. Can you work out a place to put some logic to either:

* Not resolve symlinks at all (very likely a breaking change)
* Ignore errors on resolving symlinks
* Not checking file existence on symlinks (since symlinks can point anywhere, even off-disk) - I'm unsure what we use the result for.

**Comment by travist13** [comment]
Thanks, I will look into it.

-Travis

**Comment by tjeerdbakker38** [comment]
Any news about this? I just got bitten by the exact same file :(

**Comment by travist13** [comment]
Sorry for the way long delay on this. We have a fix for this.

https://github.com/DiscUtils/DiscUtils/pull/246
