### ISSUE TITLE
NFS client fails with System.IO.EndOfStreamException

### ISSUE THREAD

**Issue by Rainmaker52** [DiscUtils/DiscUtils#285]
Hi,

I'm trying to use the NFS client implementation. I'm trying to connect from a Windows 11 client to a Rocky Linux 9 server. I've also tested with a RHEL8 server, with the same result.

Commands like showmount are indicating the share is exported and reachable.

When trying to run the bear minimum:

```
        string nfsServer = "rhel8.mshome.net";
        _ = NfsFileSystem.GetExports(nfsServer);

```
I receive a the following stacktrace:
```

Unhandled exception: System.IO.EndOfStreamException: Unable to complete read of 4 bytes
   at DiscUtils.Streams.StreamUtilities.ReadExact(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at DiscUtils.Streams.DataReader.ReadToBuffer(Int32 count)
   at DiscUtils.Streams.BigEndianDataReader.ReadUInt32()
   at DiscUtils.Nfs.PortMap2.GetPort(Int32 program, Int32 version, PortMap2Protocol protocol)
   at DiscUtils.Nfs.RpcClient.GetTransport(Int32 program, Int32 version)
   at DiscUtils.Nfs.RpcProgram.DoSend(MemoryStream ms)
   at DiscUtils.Nfs.Nfs3Mount.Exports()
   at DiscUtils.Nfs.NfsFileSystem.GetExports(String address)+MoveNext()
   at Program.MainAsync in C:\Users\Rainmaker\source\repos\NFSClient\NFSClient\Program.cs:line 86

```
I've installed DiscUtils.Complete (and .Transport, and .NFS for good measure). I've tried to use the SetupHelper.SetupTransports(), but this does not help.

In examples on the internet I saw RpcClient being created separately and then passed to the constructor of NFS3Client. However, all of these classes seem to have been marked internal now and the only (obvious) public class I could find is NfsFileSystem.

However, this does mean I'm not 100% confident I'm using the library correctly. If I'm using it wrong, please let me know.

[NFSClient.pcapng.gz](https://github.com/DiscUtils/DiscUtils/files/11824532/NFSClient.pcapng.gz)

I've attached a packet trace in case you need it.

**Comment by GuerinVII** [comment]
The correction is
`return (int)port.Port;`
instead of 
`return (int)reply.BodyReader.ReadUInt32();`
                

in PortMap2.cs line 62


Can someone update this or is it abandonware ?

**Comment by LTRData** [comment]
This repo is pretty much abandoned. I am working on a fork with lots of updated and modernized code over at https://github.com/LTRData/DiscUtils

You are welcome to post the issue there, I'll take a look at it!

**Comment by LTRData** [comment]
Just pushed new NuGet packages with this fix. `LTRData.DiscUtils.*` with version number 1.0.38.
