### ISSUE TITLE
Reading active NTFS file system

### ISSUE THREAD

**Issue by aelth** [DiscUtils/DiscUtils#81]
Hi,

I'm trying to use DiscUtils.Ntfs module for reading live/active NTFS partition, i.e. partition that the program performing the read is executed from. Drive handle and stream are successfully obtained, the library is able to parse the structures and retrieve folders, files and their content.

However, for more or less obvious reasons, the library encounters many errors and raises a lot of exceptions.
If I understand the code correctly, several structures (*Bitmap*, `NtfsFileSystem.NtfsContext.RawStream`) are wrapped around the stream that caches reads (`BlockCacheStream`). When a live system is being read, data constantly changes (especially bitmap, MFT etc.) and this invalidates the cache and creates additional MFT entries.

I first disabled caching for NTFS raw stream by setting `ReadCacheEnabled` inside `NtfsOptions` constructor to `false` (setting `NtfsOptions.ReadCacheEnabled` to `false` after `NtfsFileSystem` is created had no effect because raw stream is already created as `BlockCacheStream` inside `NtfsFileSystem` constructor). This didn't solve my issues:(

I then tried to remove all caching-related code inside `BlockCacheStream`, but errors (albeit different) still occur.
Some of the errors that appear are related to invalid references in MFT (`MasterFileTable.GetRecord` complains about MFT record with an old reference) and `NtfsFileSystem.GetDirectoryEntry` that complains about the null reference (not really sure what is causing it yet).

Couple of questions:
1. Is reading active NTFS file system supported? (I guess not:()
2. Is there a way to read an active NTFS file system that will not result in described errors?
3. Is it possible to create a VSS snapshot of the filesystem and read the snapshot with DiscUtils?

Thank you very much in advance.

Best regards,
aelth

**Comment by LordMike** [comment]
1. Not really. All filesystem implementations (NTFS and others) do not support multiple readers and writers at the same time, unless explicitly stated so. Even then, they will often at most support multiple readers but only one writer (this is possible with some structures).

2. I'm inclined to say no. I do not know the full extent of the NTFS implementation in DiscUtils, but it should be possible if an implementation were to take full advantage of the transaction logs and journals in the filesystem, but even then, its a process that is likely to be error prone. One thing you'll never get off of a live NTFS system, is the ability to read files that are written to. While all metadata actions are journaled, data actions are not. In other words, you may read file data _as it is being written_ which would give incomplete reads - and you wouldn't really be able to detect it.

3. I'm fairly confident the NTFS implementation does not support VSS. If it did, it would certainly be possible to read the snapshot, as the FS would no longer be active.

Ok. Now on to the rest. You're seeing stuff like this because DU will do some effort to validate the filesystem as it's been parsed. This helps weed out bugs and other nasties, and prevent reading corrupt data. Following a link f.ex. where the target and source don't match up is indicative of a half-write.

We _could_ implement measures to allow ignoring these errors and flaws, and allow you (and others) to read filesystms that are in use .... most of the time. But you'll neve fully guard yourself against these concurrency issues.

**Comment by aelth** [comment]
Thank you for your answer LordMike.

I'm aware of the fact that it is not possible to guarantee any kind of safety, since the disk is being accessed in a way that is not guarded by the kernel or driver structures:(
Since I'm only performing read operation, I thought that it might be possible to traverse directories and read files in a "clean" way, at least obtain valid list of files and directories and try to read files on the best-effort basis.

Do you, as an author of both tools, think that I might have more luck with [NtfsLib](https://github.com/LordMike/NtfsLib)? Examples in NtfsLib and the usage of [RawDiskLib](https://github.com/LordMike/RawDiskLib)/[DeviceIOControlLib](https://github.com/LordMike/DeviceIOControlLib) indicate that the intended use of the library is on live/active disks and partitions.

Thanks again for your help.

Best regards,
aelth

**Comment by LordMike** [comment]
No - you wont. NtfsLib was always meant as an offline parser only, so it will suffer from the same consequences. Although NtfsLib does not contain as much consistency checking, so you might get further. Running on live disks is very convenient for development :).

Reading directories and other metadata is just as errorprone as reading data for these implementations. 

But - the shadow copy path has some merit to it. Finding a way to parse shadow copies out might mean we can read a static snapshot of a live disk. This shouldn't have any flaws ('cept for already corrupt data) - but I have no idea where this info is stored; have yet to look into it.

What's your use case?

**Comment by zivillian** [comment]
We are using DiscUtils in a somehow similar scenario (#24). We are not trying to read the actual data but only the filesystem usage (which includes MFT, ClusterMap, Bitmap etc.), but until now it's working without any major issues.
If you describe your use case in some detail, I guess there will be some kind of dirty hack, which may work for you (e.g. creating a new NtfsFileSystem for each file/directory access or wrapping the stream in a caching stream).

**Comment by aelth** [comment]
It would be used as a part of a malware scanner.
Malware could hook API or native file-related operations (or even kernel functions/structures) or place some content out of reach for APIs (slack space, MFT, etc). Using raw NTFS access, I could detect some of these modifications and (to a certain degree) bypass hooks and malicious implants when traversing the disk. The idea is to completely avoid using APIs when traversing the disk and use DiscUtils.Ntfs instead (except for the initial opening of the disk handle, which is API dependant).

@zivillian - creating NtfsFileSystem for every file/directory access would probably be prohibitively expensive, but I'll give it a try today:)

There is a managed library for VSS access [AlphaVSS](http://alphavss.alphaleonis.com/) so I will consider that as an alternative.

**Comment by jol64** [comment]
I can confirm that if you create a snapshot (I am using AlphaVSS 1.3), get a SafeFileHandle via pinvoke CreateFile, then create a Stream out of that (I wasn´t using FileStream but that should do), then DiscUtils.Ntfs.NtfsFileSystem does work at least to the extent I tested...

**Comment by iyevhen** [comment]
> I can confirm that if you create a snapshot (I am using AlphaVSS 1.3), get a SafeFileHandle via pinvoke CreateFile, then create a Stream out of that (I wasn´t using FileStream but that should do), then DiscUtils.Ntfs.NtfsFileSystem does work at least to the extent I tested...

I've made same test with VSS shadow volume (AlphaVSS v1.4.0.0). Volume size is 10.64TB. Unfortunately got an error.
```
System.IO.IOException: Attempt to get an MFT record with an old reference
   at DiscUtils.Ntfs.MasterFileTable.GetRecord(FileRecordReference fileReference)
   at DiscUtils.Ntfs.File.LoadAttributes()
   at DiscUtils.Ntfs.NtfsFileSystem..ctor(Stream stream)
```

```
SectorsPerCluster     : 8 (0x8);
BytesPerSector        : 512 (0x200);
ClusterSize           : 4096 (0x1000);
TotalNumberOfClusters : 2883550463 (0xABDF7CFF);
NumberOfFreeClusters  : 666053947 (0x27B32D3B);

NTFS_VOLUME_DATA_BUFFER
      |_VolumeSerialNumber               16046907894348747615 (0xDEB211B5B211935F)
      |_NumberSectors                    23068403711 (0x55EFBE7FF)
      |_TotalClusters                    2883550463 (0xABDF7CFF)
      |_FreeClusters                     666055051 (0x27B3318B)
      |_TotalReserved                    80 (0x50)
      |_BytesPerSector                   512 (0x200)
      |_BytesPerCluster                  4096 (0x1000)
      |_BytesPerFileRecordSegment        1024 (0x400)
      |_ClustersPerFileRecordSegment     0 (0x0)
      |_MftValidDataLength               145599234048 (0x21E6640000)
      |_MftStartLcn                      786432 (0xC0000)
      |_Mft2StartLcn                     2 (0x2)
      |_MftZoneStart                     1730598048 (0x6726D4A0)
      |_MftZoneEnd                       1730598080 (0x6726D4C0)
VOLUME_DISK_EXTENTS {#1} 
     |_NumberOfDiskExtents     1 (0x1)
     |_Extents {#2}                 1 item(s)
            |_DISK_EXTENT {#3} 
                   |_DiskNumber         1 (0x1)
                   |_StartingOffset     135266304 (0x8100000)
                   |_ExtentLength       11811022700544 (0xABDF7D00000)
```

> 3\. I'm fairly confident the NTFS implementation does not support VSS. If it did, it would certainly be possible to read the snapshot, as the FS would no longer be active.

Taking into account what LordMike said, this is true. 
Not sure how to resolve this issue now. Other volumes are ok.

**Comment by R030t1** [comment]
I'm interested in this issue as well. I've successfully set up volume shadows with AlphaVSS and can open the resulting `SnapshotDeviceObject` with AlphaFS, but it seems inappropriate for passing to `NtfsFileSystem`. Can you detail what I should be doing to open the snapshot to read the NTFS headers?

The only error I get is an extremely unspecific IOException.

**Comment by jol64** [comment]
> I've made same test with VSS shadow volume (AlphaVSS v1.4.0.0). Volume size is 10.64TB. Unfortunately got an error.

This is speculative, but 10.64TB is likely causing an issue due to singed/unsigned int32 overflow. Beyond 8TB this is becoming an issue. In fact the largest NTFS volume I run is 2TB, all larger volumes are ReFS.

> Can you detail what I should be doing to open the snapshot to read the NTFS headers?

It is really that simple: you wrap the device that you get from AlphaVSS into a Stream and pass that to DiscUtils. If you need more details you can contact me for consulting at reasonable fees.

**Comment by sspry-ip** [comment]
@jol64: This is ultimately for an open source project, so if you have some spare time I'd appreciate a comment on the code around here: https://github.com/R030t1/NtfsList/blob/master/Program.cs#L78. I've also tried using AlphaFS's `File.OpenRead` method.

`CreateFile` does not report error and the stream I open seems to be readable. If I need to debug the guts of `NtfsFileSystem` I can move on to that, but I'm hoping you can give me at least a yes/no about how close the code is to the code you got working.

**Comment by R030t1** [comment]
@jol64: This is ultimately for an open source project, so if you have some spare time I'd appreciate a comment on the code around here: https://github.com/R030t1/NtfsList/blob/master/Program.cs#L78. I've also tried using AlphaFS's File.OpenRead method.

CreateFile does not report error and the stream I open seems to be readable. If I need to debug the guts of NtfsFileSystem I can move on to that, but I'm hoping you can give me at least a yes/no about how close the code is to the code you got working.

**Comment by jol64** [comment]
> @jol64: This is ultimately for an open source project, so if you have some spare time I'd appreciate a comment on the code around here: https://github.com/R030t1/NtfsList/blob/master/Program.cs#L78. I've also tried using AlphaFS's `File.OpenRead` method.

@R030t1 A personal repository without license and mission? Come on... and you didn´t even read my statement of what to do carefully.

> This is speculative, but 10.64TB is likely causing an issue due to singed/unsigned int32 overflow. Beyond 8TB this is becoming an issue. In fact the largest NTFS volume I run is 2TB, all larger volumes are ReFS.

I tried to validate that hypothesis, but failed - which is good news. My test was:
- create a .vhdx of 10TB and format one partion with NTFS.
- I wrote a litte program that created some files and called SetFileSize with a random number for each. 
- run my application on that disk

Essentially this allocated almost all clusters with zero contents (as .vhdx allocates only non-zero blocks). The resulting .vhdx is less than 1GB but the volume claims to have >9TB allocated. With that disk I ran a test on my application which in turn uses a forked version of DiscUtils (April 2018) and I discovered several 32bit issues in my own code but none so far in DiskUtils. 
Unfortunately this does not prove absence of errors, but also there is no evidence of a bug in the code I excercised, which is of course only a subset of DiscUtils.

> I've made same test with VSS shadow volume (AlphaVSS v1.4.0.0). Volume size is 10.64TB. Unfortunately got an error.
> 
> ```
> System.IO.IOException: Attempt to get an MFT record with an old reference
>    at DiscUtils.Ntfs.MasterFileTable.GetRecord(FileRecordReference fileReference)
>    at DiscUtils.Ntfs.File.LoadAttributes()
>    at DiscUtils.Ntfs.NtfsFileSystem..ctor(Stream stream)
> ```

@iyevhen I can access MFT records, but my code uses modifications. If you are willing to share your source fragment rather than the exception I might throw it at my stack.

**Comment by R030t1** [comment]
@jol64 It's not anywhere close to done, that is a testcase. Do you mind helping or do you get off by being a massive prick in public? The end goal is to have a backup program that works on live volumes and doesn't suck.

>I can confirm that if you create a snapshot (I am using AlphaVSS 1.3), get a SafeFileHandle via pinvoke CreateFile, then create a Stream out of that (I wasn´t using FileStream but that should do), then DiscUtils.Ntfs.NtfsFileSystem does work at least to the extent I tested...

I'm getting a `SafeFileHandle` via PInvoke's `CreateFile`. If you've got special sauce I have no idea what it is.

**Comment by jol64** [comment]
> @jol64 It's not anywhere close to done, that is a testcase. If I provided a whole project no doubt you'd complain I didn't provide a testcase. Do you mind helping or do you get off by being a massive prick in public? The end goal is to have a backup program that works on live volumes and doesn't suck.

I.e. ultimately you are a competitor. Sorry, no.
